blank_issues_enabled: false
contact_links:
- name: The Things Network Community Forum
  url: https://www.thethingsnetwork.org/forum/c/application-development/15
  about: Please ask and answer questions on the forum.
