services:
  memcached:
    image: memcached:1
  benthos:
    depends_on:
      - memcached
    image: jeffail/benthos:3
    networks:
      - default
      - ingest
    configs:
      - benthos.yaml

configs:
  benthos.yaml:
    file: ./benthos.yaml

networks:
  ingest:
    external: true
